service: default
runtime: nodejs18
instance_class: F1

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

beta_settings:
  cloud_sql_instances: "PROJECT:REGION:INSTANCE"

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "sm://PROJECT/DATABASE_URL/latest"
  GCP_STORAGE_BUCKET: "digital-menu-455517-media" 