service: default
runtime: nodejs20
instance_class: F1

entrypoint: bash entrypoint.sh

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

beta_settings:
  cloud_sql_instances: "digital-menu-455517:us-central1:digital-menu-db"

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "sm://digital-menu-455517/DATABASE_URL/latest"
  GCP_STORAGE_BUCKET: "digital-menu-455517-media"

# Force redeploy to fetch latest secrets 