runtime: nodejs20

instance_class: F1

env_variables:
  DATABASE_URL: 'postgresql://postgres:JAFgQKBgQDZTW@/menuview_db?host=/cloudsql/digital-menu-455517:us-central1:digital-menu-db'
  GCP_PROJECT_ID: 'digital-menu-455517'
  GCP_STORAGE_BUCKET: 'digital-menu-455517-uploads'

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.65

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300