name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: digital-menu-455517
  GAR_LOCATION: us-central1
  SERVICE_NAME: digital-menu-backend
  REGION: us-central1

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |-
          docker build --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          platform: 'managed'
          allow_unauthenticated: true
          min_instances: 0
          max_instances: 1
          cloud_sql_instances: '${{ env.PROJECT_ID }}:${{ env.REGION }}:digital-menu-db'
          env_vars: |
            NODE_ENV=production
            GCP_PROJECT_ID=${{ env.PROJECT_ID }}
            GCP_STORAGE_BUCKET=${{ env.PROJECT_ID }}-uploads
            DATABASE_URL=postgresql://postgres:JAFgQKBgQDZTW@/menuview_db?host=/cloudsql/${{ env.PROJECT_ID }}:${{ env.REGION }}:digital-menu-db

      - name: Show Cloud Run URL
        run: echo "Deployment successful. URL: ${{ steps.deploy.outputs.url }}" 