name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  PROJECT_ID: digital-menu-455517
  GAR_LOCATION: us-central1
  SERVICE_NAME: digital-menu-backend
  REPO_NAME: digitalmenu # The name of the Artifact Registry repository
  REGION: us-central1
  INSTANCE_NAME: digital-menu-db # The name of the Cloud SQL instance

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Build and Push Docker image with Cloud Build
        id: build
        run: |-
          gcloud builds submit --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .

      - name: Deploy to Cloud Run
        id: deploy
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" \
            --region ${{ env.REGION }} \
            --add-cloudsql-instances=${{ env.PROJECT_ID }}:${{ env.REGION }}:${{ env.INSTANCE_NAME }} \
            --update-secrets=DATABASE_URL=DATABASE_URL:latest \
            --allow-unauthenticated \
            --project=${{ env.PROJECT_ID }}